In [10]:
import numpy as np
a = np.linspace(3.5,4,15)
a

array([3.5       , 3.53571429, 3.57142857, 3.60714286, 3.64285714,
       3.67857143, 3.71428571, 3.75      , 3.78571429, 3.82142857,
       3.85714286, 3.89285714, 3.92857143, 3.96428571, 4.        ])

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
b = np.random.randint(50,100,25).reshape(5,5)
b

array([[79, 98, 76, 70, 70],
       [79, 93, 97, 56, 99],
       [60, 52, 58, 94, 61],
       [72, 66, 57, 82, 76],
       [86, 91, 73, 91, 54]])

In [22]:
c = b.reshape(1,5,5)
c

array([[[79, 98, 76, 70, 70],
        [79, 93, 97, 56, 99],
        [60, 52, 58, 94, 61],
        [72, 66, 57, 82, 76],
        [86, 91, 73, 91, 54]]])

In [44]:
import pandas as pd

student=pd.read_csv("C:\\Users\\97150\\Downloads\\students.csv")
student

Name  Age  Grade  Score
0  Alice   15     10   85.0
1    Bob   14      9    NaN
2  Carol   15     10   78.0
3   Dave   14      9   55.0
4  Alice   15     10   85.0
5    Eve   14      9   45.0

In [46]:
std_clean = student.fillna(0)
std_clean 

Name  Age  Grade  Score
0  Alice   15     10   85.0
1    Bob   14      9    0.0
2  Carol   15     10   78.0
3   Dave   14      9   55.0
4  Alice   15     10   85.0
5    Eve   14      9   45.0

In [80]:
d = std_clean.drop_duplicates()
d

Name  Age  Grade  Score
0  Alice   15     10   85.0
1    Bob   14      9    0.0
2  Carol   15     10   78.0
3   Dave   14      9   55.0
5    Eve   14      9   45.0

In [60]:
std_clean1.describe()


Age      Grade      Score
count   5.000000   5.000000   5.000000
mean   14.400000   9.400000  52.600000
std     0.547723   0.547723  33.634803
min    14.000000   9.000000   0.000000
25%    14.000000   9.000000  45.000000
50%    14.000000   9.000000  55.000000
75%    15.000000  10.000000  78.000000
max    15.000000  10.000000  85.000000

#Stack the two 2D NumPy arrays C = np.array([[1, 2], [3, 4]]) and D = np.array([[5, 6], [7, 8]]) horizontally

In [121]:
C = np.array([[1, 2], [3, 4]]) 
D = np.array([[5, 6], [7, 8]]) 
result=np.hstack([C,D])
result

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [124]:
d

Name  Age  Grade  Score
0  Alice   15     10   85.0
1    Bob   14      9    0.0
2  Carol   15     10   78.0
3   Dave   14      9   55.0
5    Eve   14      9   45.0

In [148]:

d['average']=np.where(d['Score']> 70,'high','low')
d

C:\Users\97150\AppData\Local\Temp\ipykernel_10428\3359226175.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d['average']=np.where(d['Score']> 70,'high','low')


Name  Age  Grade  Score average
0  Alice   15     10   85.0    high
1    Bob   14      9    0.0     low
2  Carol   15     10   78.0    high
3   Dave   14      9   55.0     low
5    Eve   14      9   45.0     low

In [144]:
# Adding a new column 'G' based on a condition
df['G'] = df['A'].apply(lambda x: 'High' if x > 2 else 'Low')

print(df)
 d['average'] = np.where(d['Score']x> 70, 'High', 'low')

IndentationError: unexpected indent (1359866550.py, line 5)