  print("numpy")

In [4]:
import numpy as np

In [8]:
print(np)

np


In [195]:
import numpy as np
array1 = np.arange(0,100,10)
print("Array from 0 to 100:",   array1)


Array from 0 to 100: [ 0 10 20 30 40 50 60 70 80 90]


In [37]:

array2 = np.linspace(0, 100,10,False)
print("10 evenly spaced values from 0 to 100:", array2)


10 evenly spaced values from 0 to 100: [ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


# excluding end point


In [29]:

array3= np.linspace(0, 1, num=5, endpoint=False)

print("5 values from 0 to 1 (excluding endpoint):", array3)


5 values from 0 to 1 (excluding endpoint): [0.  0.2 0.4 0.6 0.8]


In [71]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3,k=1)
print("3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [198]:
import numpy as np
random_array = np.random.rand(3)
print(random_array)


[0.07978094 0.83347446 0.83463743]


In [67]:
import numpy as np
random_array = np.random.randint(10, 20,(3,3))
print(random_array)

[[14 18 18]
 [14 18 14]
 [13 10 13]]


In [200]:
# Generate an array of 5 random numbers from a normal distribution
random_array = np.random.normal(loc=0, scale=1, size=5)
print(random_array)


[-0.86974992 -1.0962084  -0.1040069   0.38151095  0.51328466]


In [81]:
import numpy as np
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [85]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [55]:
import numpy as np
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
import numpy as np
m = ([[1,2,3],
      [3,4,5],
      [4,5,6]])
diagonal=np.diag(m,k=1)
print(diagonal)

[2 5]


In [65]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [79]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [125]:
np.diag(a,k=1)

array([2, 6])

# reshape 
change shape of the array make it to different dimensions

In [132]:

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((3, 2))
print(reshaped_array)


[[1 2]
 [3 4]
 [5 6]]


In [136]:
array = np.array([1,2,3,4,5,6])
re_array=array.reshape((2,3,1))
print(re_array)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


Using -1 to infer a dimension: If one of the dimensions is -1, NumPy will automatically calculate it based on the size of the array and the other dimensions.

In [140]:
array = np.array([1,2,3,4,5,6])
re_array=array.reshape(-1,2)
print(re_array)

[[1 2]
 [3 4]
 [5 6]]


# ravel()
it used to flatten an array 
to an one diamensional array

In [145]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
flattened_array = array.ravel()
print(flattened_array)



[1 2 3 4 5 6]


In [161]:
array1=np.array([[[1,2],[3,3]],
                 [[7,8],[2,6]]])
flatten=array1.ravel()
print(flatten)

[1 2 3 3 7 8 2 6]


# flatten
it create new memmory array but in ravel it changes the original array

In [165]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], 
                  [4, 5, 6]])

# Use ravel() to flatten the array
raveled_array = array.ravel()

# Modify the first element of the raveled array
raveled_array[0] = 10  

print("Raveled Array:")
print(raveled_array)  # Output: [10  2  3  4  5  6]
print("Original Array After ravel():")
print(array)         # Output: [[10  2  3]
                     #          [ 4  5  6]]


Raveled Array:
[10  2  3  4  5  6]
Original Array After ravel():
[[10  2  3]
 [ 4  5  6]]


In [167]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], 
                  [4, 5, 6]])

# Use ravel() to flatten the array
raveled_array = array.flatten()

# Modify the first element of the raveled array
raveled_array[0] = 10  

print("Raveled Array:")
print(raveled_array)  # Output: [10  2  3  4  5  6]
print("Original Array After flatten():")
print(array)         # Output: [[10  2  3]
                     #          [ 4  5  6]]


Raveled Array:
[10  2  3  4  5  6]
Original Array After flatten():
[[1 2 3]
 [4 5 6]]


# 3 dimensional array

In [180]:
arr = np.array([
    [[2,3],[3,4]],
    [[4,5],[6,7]]
])


[[[2 3]
  [3 4]]

 [[4 5]
  [6 7]]]


In [184]:
arr

array([[[2, 3],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr.shape

(12,)

In [17]:
arr2=arr.reshape(2,2,3)
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
arr2.shape

(2, 2, 3)

In [280]:
arr3=arr2.reshape(-1)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# concatenation 
adding two array

In [285]:
ar1 =np.arange(1,10)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [303]:
b=np.arange(9,18).reshape(3,3)
b


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [305]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  9, 10, 11],
       [ 4,  5,  6, 12, 13, 14],
       [ 7,  8,  9, 15, 16, 17]])

In [309]:
np.concatenate((a,b),axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [311]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [313]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

it will create 2 dimesional array 

In [315]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [ 9, 10, 11]],

       [[ 4,  5,  6],
        [12, 13, 14]],

       [[ 7,  8,  9],
        [15, 16, 17]]])

In [320]:
np.stack((a,b),axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [322]:
ar1 =np.arange(1,10)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [324]:
b=np.arange(9,18).reshape(3,3)
b


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [326]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [328]:
np.hstack((a,b))

array([[ 1,  2,  3,  9, 10, 11],
       [ 4,  5,  6, 12, 13, 14],
       [ 7,  8,  9, 15, 16, 17]])

In [330]:
np.dstack((a,b))

array([[[ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14]],

       [[ 7, 15],
        [ 8, 16],
        [ 9, 17]]])

# array splitting
split array 

if the array doesnt have equal divisions it show value error

array_split : it will split accorndingly 

h split 
.
.
array-split(array,no of splits)
# v split - a minimum of 2 d is needed 

In [26]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.array_split(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [34]:
np.hsplit(a,2)   

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [38]:
np.hsplit(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [35]:
a=np.arange(0,12).reshape((3,2,2))
a
#np.vsplit(a,3)



array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [52]:
a= np.array([[1,2,3],
            [2,3,4,]])
a
             

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[2, 3, 4]])]

### mathematic funcions in numpy 
universal functions

In [12]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8])
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.sqrt(np1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

In [8]:
np.exp(np1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03])

In [10]:
np.sum(np1)

36

In [14]:
np.min(a)

1

In [16]:
np.max(a)

8

In [18]:
np.std(a)

2.29128784747792

In [20]:
np.mean(a)

4.5

# random numbers

In [109]:
a= np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
np.random.rand(2,10)

array([[0.97576809, 0.5521458 , 0.55796667, 0.33672244, 0.64769735,
        0.30415326, 0.56859515, 0.98288258, 0.09679177, 0.18317278],
       [0.19235012, 0.2844785 , 0.06422586, 0.69428797, 0.97536605,
        0.89758877, 0.0994107 , 0.98146423, 0.65696599, 0.19557261]])

In [113]:
np.random.randint(10,20,10)

array([10, 19, 10, 10, 14, 13, 10, 18, 16, 17])

In [183]:
np.random.normal(0,8)

15.028854643673697

In [177]:
np.random.choice(a)

8

In [81]:
np.random.permutation(a)

array([2, 5, 7, 3, 4, 6, 1, 8])

# loops in numpy


In [86]:
a=np.array([1,2,3,4,5,6,7,8])
for x in a:
    print(x)

1
2
3
4
5
6
7
8


In [279]:
b=np.array([[1,2,3],[4,5,6]])
for x in b:
    #print(x)
    for y in x:
        print(y)
       

1
2
3
4
5
6


In [102]:
c=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
for x in c:
   # print(c)
    for j in x:
       # print(j)
        for k in j:
            print(k)
    

1
2
3
4
5
6
7
8
9


In [112]:
c=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
for x in np.nditer(c):
    print(x)
    
    

1
2
3
4
5
6
7
8
9


# ndenumerate
foe enumeratng with index

In [10]:
import numpy as np
a=np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
for index in np.ndenumerate(a):
    print(index)


((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((0, 3), 3)
((0, 4), 4)
((0, 5), 5)
((1, 0), 6)
((1, 1), 7)
((1, 2), 8)
((1, 3), 9)
((1, 4), 10)
((1, 5), 11)


In [30]:
for i in range(len(a)):
    print(f"index: {i}, value: {a[i]}")
    

index: 0, value: [0 1 2 3 4 5]
index: 1, value: [ 6  7  8  9 10 11]


In [68]:
for i in np.ndenumerate(a):
    print(i)





((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((0, 3), 3)
((0, 4), 4)
((0, 5), 5)
((1, 0), 6)
((1, 1), 7)
((1, 2), 8)
((1, 3), 9)
((1, 4), 10)
((1, 5), 11)


In [40]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [44]:
b=np.arange(12).reshape(2,3,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [60]:
for index in range(len(a)):
    print(f"index: {index},value: {a[i]}")


index: 0,value: [ 6  7  8  9 10 11]
index: 1,value: [ 6  7  8  9 10 11]


# indexing using  .ndindex

In [64]:
for index in np.ndindex(a.shape):
    print(f"index: {index},value: {a[index]}")

index: (0, 0),value: 0
index: (0, 1),value: 1
index: (0, 2),value: 2
index: (0, 3),value: 3
index: (0, 4),value: 4
index: (0, 5),value: 5
index: (1, 0),value: 6
index: (1, 1),value: 7
index: (1, 2),value: 8
index: (1, 3),value: 9
index: (1, 4),value: 10
index: (1, 5),value: 11


# indexing using enumerate

In [88]:
for i,v in np.ndenumerate(a):
    print(f"index: {i},value: {v}")



index: (0, 0),value: 0
index: (0, 1),value: 1
index: (0, 2),value: 2
index: (0, 3),value: 3
index: (0, 4),value: 4
index: (0, 5),value: 5
index: (1, 0),value: 6
index: (1, 1),value: 7
index: (1, 2),value: 8
index: (1, 3),value: 9
index: (1, 4),value: 10
index: (1, 5),value: 11


# looping over multiple arrays
# zip()

In [107]:
import pandas as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])


In [109]:
for a, b in zip(a1, a2):
    print(f"a1: {a}, a2: {b}")

a1: 1, a2: 4
a1: 2, a2: 5
a1: 3, a2: 6


In [111]:
for a,b in zip(a1,a2):
    print(a,b)

1 4
2 5
3 6


# nditer in multiple arrays

In [174]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [176]:
b=np.array([[10],[20]])
b

array([[10],
       [20]])

In [180]:
for x,y in np.nditer([a,b]):
    print(f"a: {x},b: {y}")

a: 1,b: 10
a: 2,b: 10
a: 3,b: 10
a: 1,b: 20
a: 2,b: 20
a: 3,b: 20


In [190]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
b=np.array([[1],[78]])
b

array([[ 1],
       [78]])

In [200]:
for x,y in np.nditer([a,b]):
    print(f"a: {x},b: {y}")

a: 1,b: 1
a: 2,b: 1
a: 3,b: 1
a: 4,b: 78
a: 5,b: 78
a: 6,b: 78


In [206]:
a1=np.array([[[1,2,3],[4,5,6]]])
np.shape(a1)

(1, 2, 3)

In [214]:
a2=np.array([[[10], [20]], [[30], [40]]])  
np.shape(a2)

(2, 2, 1)

In [220]:
for x,y in np.nditer([a1,a2]):
    print(x,y)

1 10
2 10
3 10
4 20
5 20
6 20
1 30
2 30
3 30
4 40
5 40
6 40


# vectorisation
without using loops

In [223]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
a+b   

array([ 6,  8, 10, 12, 14])

In [225]:
a*b

array([ 5, 12, 21, 32, 45])

In [227]:
a+10

array([11, 12, 13, 14, 15])

In [229]:
a*2

array([ 2,  4,  6,  8, 10])

In [235]:
a[a<3]


array([1, 2])

In [241]:
a[a>=3]

array([3, 4, 5])

# condtional looping in arrays
# use np.where()

In [250]:
import numpy as np
a=np.array([1,2,3,4,5])
a[a<=3]*=2
print(a)


[2 4 6 4 5]


here upto 3 have been doubled and rest of number is written as its is

1* 2 ,2* 2 ,3*2 ,4 ,5

In [256]:
a=np.array([1,2,3,4,5])
np.where(a>3,a*2,a)

array([ 1,  2,  3,  8, 10])

Replacing explicit loops with NumPy functions like np.sum(), np.mean(), and using np.vectorize().									

In [259]:
a = np.array([1, 2, 3, 4])

# Traditional loop for calculating the mean
total = 0
for x in a:
    total += x
mean_value = total / len(a)
print(mean_value)  # Output: 2.5


2.5


In [261]:
mean_value = np.mean(a)
print(mean_value)  # Output: 2.5


2.5


In [263]:
import numpy as np

a = np.array([1, 2, 3, 4])

# Traditional loop for summing elements
total = 0
for x in a:
    total += x
print(total)  # Output: 10


10


In [265]:
total = np.sum(a)
print(total)  # Output: 10


10


In [5]:
import numpy as np
a = np.array([10,12])
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x,y in np.nditer([a,b]):
    print(x,y)

10 1
12 2
10 3
12 4
10 5
12 6
10 7
12 8
