In [17]:
import numpy as np
a = np.arange(0,10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [19]:
a1=np.split(a,4)
a1

[array([   0,    1,    2, ..., 2497, 2498, 2499]),
 array([2500, 2501, 2502, ..., 4997, 4998, 4999]),
 array([5000, 5001, 5002, ..., 7497, 7498, 7499]),
 array([7500, 7501, 7502, ..., 9997, 9998, 9999])]

In [91]:
a = np.array([[ 1 , 2 , 3],[ 4 , 5,  6],[ 7,  8 , 9],[10, 11, 12]])
shuffle = np.random.permutation(a)
shuffle

array([[ 4,  5,  6],
       [ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [101]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   24     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston

In [103]:
data2 = df[df['City']=='New York']
data2

Name  Age      City
0  Alice   24  New York

In [79]:
import pandas as pd
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [24, 30]
})

df2 = pd.DataFrame({
    'Name': ['Charlie', 'David'],
    'Age': [22, 35]
})
concat= pd.concat([df1,df2])
concat

Name  Age
0    Alice   24
1      Bob   30
0  Charlie   22
1    David   35

In [105]:
A = np.array([[4, 2],
              [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [107]:
a = np.eye(3)

a 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])